[package]
name = "elevate-lib"
version = "0.1.8"
authors = ["whatsacomputertho"]
edition = "2021"
description = "An elevator simulation library for Rust"
readme = "README.md"
homepage = "https://docs.rs/elevate-lib"
repository = "https://github.com/whatsacomputertho/elevate"
license-file = "LICENSE"
keywords = ["elevator","simulation","library","rust","elevate"]
categories = ["simulation","visualization"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
termcolor = "1.4.0"
statrs = "0.16.0"
